// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';

// https://astro.build/config
// The sitemap is generated by src/pages/sitemap.xml.ts (served at /sitemap.xml).
export default defineConfig({
  site: 'https://cookedfinance.com',
  vite: {
    plugins: [tailwindcss()],
  },
});
